### ISSUE TITLE
[DSpot][Descartes] Add tooltips to both DSpot and Descartes Wizard page form entries that explains the purpose of different fields

### ISSUE THREAD

**Issue by jesus-gorronogoitia** [STAMP-project/eclipse-ide#3]
#### Characteristics
- **Issue Type**: feature
- **Reproducibility**: N/A
- **Severity**: feature
- **Tool/Service/Component**: Descartes, Dspot
- **Execution Environment**: Linux Tumbleweed, Eclipse Oxygen
- **Reporter**: Jesús Gorroñogoitia <jesus.gorronogoitia@atos.net>

#### Description
Add tooltips to both DSpot and Descartes Wizard page form fields that explains their purpose. Add the tooltips so they are rendered when hovering the mouse pointer over the field label or over the buttons.
Take the tooltip message from a properties files, so the tooltips can be easily updated without requiring to edit code and compile.

#### Steps to reproduce
N/A
#### [Help on issue template](https://github.com/STAMP-project/eclipse-ide/blob/master/.github/ISSUE_DOC.md) 
Preview to follow the link or open file .github/ISSUE_DOC.md

**Comment by jesus-gorronogoitia** [comment]
I confirm tooltips for some buttons, but I don't see tooltips when the mouse is hovering over some labels describing some fields. Could be possible to add tooltips to labels?
If so,
Descartes wizard: add tooltips to labels to manage configurations (load, create), path of the project and POM.file. Also to select a project button.
DSpot wizard: add tooltips to all labels in all wizards. Also to select test button in second page. Also to clean list button in advanced options wizard.

Note: Select Folder button for path pit result looks disabled. 
Note: pit should be PIT
Note: All labels should start with capital letter.
Note: advanced options wizard page has title but not a introductory label, as the other wizard pages

**Comment by RicardoTej** [comment]
I have added more tooltips to Descartes wizard following the instructions in your comment

**Comment by RicardoTej** [comment]
DSpot ready, the Select Button for path PIT is activated if PitMutantScoreSelector is selected in the criterion combo in page two
