### ISSUE TITLE
[DSpot][Descartes] Edit Wizard titles and descriptions

### ISSUE THREAD

**Issue by jesus-gorronogoitia** [STAMP-project/eclipse-ide#4]
#### Characteristics
- **Issue Type**: feature
- **Reproducibility**: N/A
- **Severity**: feature
- **Tool/Service/Component**: DSpot and Descartes wizards
- **Execution Environment**: Linux Tumbleweed, Eclipse Oxygen
- **Reporter**: Jesús Gorroñogoitia <jesus.gorronogoitia@atos.net>

#### Description
Update Title and description in Wizard pages for DSpot and Descartes:
DSpot Wizard:
Page 1: 
Title: Project configuration
Description: Information about the project
Page 2: 
Title: DSpot execution
Description: Configuration of the DSpot execution
Descartes Wizard:
Title: Descartes configuration
Description: Configuration of Descartes mutators

#### [Help on issue template](https://github.com/STAMP-project/eclipse-ide/blob/master/.github/ISSUE_DOC.md) 
Preview to follow the link or open file .github/ISSUE_DOC.md

**Comment by RicardoTej** [comment]
Edited, thank you.
