### ISSUE TITLE
Duplicated STAMP top menu, one entry for DSpot, another for Descartes

### ISSUE THREAD

**Issue by jesus-gorronogoitia** [STAMP-project/eclipse-ide#5]
#### Characteristics
- **Issue Type**: bug
- **Reproducibility**: always
- **Severity**: minor
- **Tool/Service/Component**: DSpot Plugin for Eclipse, Descartes plugin for Eclipse
- **Execution Environment**: Linux Tumbleweed, Eclipse Oxygen
- **Reporter**: Jesús Gorroñogoitia <jesus.gorronogoitia@atos.net>

#### Description
When both plugins (DSpot and Descartes) are installed, there are two STAMP top menus, once including a Dspot submenu, another one including a Descartes submenu

#### Steps to reproduce
Install both plugins using the STAMP update site and observe the Eclipse top menu

I guess this is cause because both plugins declare the same top menu

#### [Help on issue template](https://github.com/STAMP-project/eclipse-ide/blob/master/.github/ISSUE_DOC.md) 
Preview to follow the link or open file .github/ISSUE_DOC.md

**Comment by jesus-gorronogoitia** [comment]
This is not happening in the contextual menu, where only one STAMP submenu is included, because both plugins use the same menu identifier. Do the same for the top menu.

**Comment by RicardoTej** [comment]
Fixed, now both plugins use the same identifier for the top menu.
