### ISSUE TITLE
[DSpot Wizard] NPE when locating the default page image

### ISSUE THREAD

**Issue by jesus-gorronogoitia** [STAMP-project/eclipse-ide#6]
#### Characteristics
- **Issue Type**: bug
- **Reproducibility**: always
- **Severity**: block
- **Tool/Service/Component**: DSpot plugin for Eclipse
- **Execution Environment**: Linux Tumbleweed, Eclipse Oxygen
- **Reporter**: Jesús Gorroñogoitia <jesus.gorronogoitia@atos.net>

#### Description
DSpot Wizard does not appear. 
Debugging console shows the following exception:

> org.eclipse.e4.core.di.InjectionException: java.lang.NullPointerException
> 	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:65)
> 	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:305)
> 	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:239)
> 	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:132)
> 	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:152)
> 	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:494)
> 	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:487)
> 	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:210)
> 	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:431)
> 	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.handleWidgetSelection(AbstractContributionItem.java:446)
> 	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.lambda$2(AbstractContributionItem.java:472)
> 	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
> 	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5348)
> 	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1348)
> 	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4602)
> 	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4183)
> 	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1150)
> 	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
> 	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1039)
> 	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
> 	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:680)
> 	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
> 	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)
> 	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
> 	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:151)
> 	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
> 	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
> 	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
> 	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
> 	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
> 	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
> 	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
> 	at org.eclipse.equinox.launcher.Main.main(Main.java:1472)
> Caused by: java.lang.NullPointerException
> 	at org.eclipse.core.internal.runtime.FindSupport.findInPlugin(FindSupport.java:233)
> 	at org.eclipse.core.internal.runtime.FindSupport.find(FindSupport.java:100)
> 	at org.eclipse.core.internal.runtime.FindSupport.find(FindSupport.java:61)
> 	at org.eclipse.core.runtime.FileLocator.find(FileLocator.java:85)
> 	at eu.stamp.wp4.dspot.wizard.DSpotWizard.getDefaultPageImage(DSpotWizard.java:76)
> 	at org.eclipse.jface.wizard.WizardPage.getImage(WizardPage.java:150)
> 	at org.eclipse.jface.wizard.WizardDialog.updateTitleBar(WizardDialog.java:1420)
> 	at org.eclipse.jface.wizard.WizardDialog.update(WizardDialog.java:1273)
> 	at org.eclipse.jface.wizard.WizardDialog.showStartingPage(WizardDialog.java:1228)
> 	at org.eclipse.jface.wizard.WizardDialog.createContents(WizardDialog.java:582)
> 	at org.eclipse.jface.window.Window.create(Window.java:426)
> 	at org.eclipse.jface.dialogs.Dialog.create(Dialog.java:1096)
> 	at org.eclipse.jface.window.Window.open(Window.java:783)
> 	at eu.stamp.wp4.dspot.wizard.utils.DSpotWizardHandler.execute(DSpotWizardHandler.java:41)
> 	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:291)
> 	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:92)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:55)
> 	... 37 more
> 
It seems a problem to load the page default icon.

#### Steps to reproduce
Launch DSpot Wizard

#### [Help on issue template](https://github.com/STAMP-project/eclipse-ide/blob/master/.github/ISSUE_DOC.md) 
Preview to follow the link or open file .github/ISSUE_DOC.md

**Comment by jesus-gorronogoitia** [comment]
@RicardoTej solution is easy: you are developing in Windows and code tries to open path: "images/Stamp.png"
but the image name is stamp.png, so it fails in Linux. It doesn't in Windows since it does not distinguish character cases. Please, check that all file names and code references are in lowercase. Thanks.

**Comment by jesus-gorronogoitia** [comment]
There is another problem with PLUGIN_NAME in DSpotWizardConstants, which should be:
public final static String PLUGIN_NAME = "eu.stamp.eclipse.dspot.wizard";

**Comment by RicardoTej** [comment]
Fixed, it was just a problem with a capital letter,
 and I have changed PLUGIN_NAME to be right.
Thank you.
